# Generated by Django 6.0.1 on 2026-10-03 12:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('movies', '0005_personal_library'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LobbySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('matched', 'Matched'), ('exhausted', 'Exhausted'), ('cancelled', 'Cancelled')], default='waiting', max_length=15)),
                ('rules_version', models.CharField(default='classic-v1', max_length=20)),
                ('quiz_version', models.CharField(default='v1', max_length=20)),
                ('quiz_snapshot', models.JSONField(default=dict)),
                ('resolved_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobby_sessions', to='groups.group')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_lobbies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LobbyParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('joined', 'Joined'), ('active', 'Active')], default='joined', max_length=10)),
                ('quiz_answers', models.JSONField(default=dict)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobby_participations', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='lobby.lobbysession')),
            ],
        ),
        migrations.CreateModel(
            name='LobbyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('system', 'System'), ('manual', 'Manual')], default='system', max_length=10)),
                ('position', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('current', 'Current'), ('vetoed', 'Vetoed'), ('watched', 'Watched'), ('matched', 'Matched')], default='queued', max_length=10)),
                ('pitch', models.TextField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lobby_cards', to='movies.movie')),
                ('picked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picked_cards', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='lobby.lobbysession')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WatchlistOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watch_offer', to='lobby.lobbycard')),
            ],
        ),
        migrations.CreateModel(
            name='WatchlistOfferResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('added', 'Added to group'), ('dismissed', 'Dismissed'), ('closed', 'Closed')], default='pending', max_length=10)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='lobby.watchlistoffer')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_responses', to='lobby.lobbyparticipant')),
            ],
        ),
        migrations.CreateModel(
            name='LobbyBallot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('want', 'Want to watch'), ('watched', 'Watched it'), ('not_interested', 'Not interested')], max_length=15)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='lobby.lobbycard')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='lobby.lobbyparticipant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('card', 'participant'), name='unique_ballot_per_card_participant')],
            },
        ),
        migrations.AddIndex(
            model_name='lobbysession',
            index=models.Index(fields=['group', 'status'], name='lobby_lobby_group_i_c5b726_idx'),
        ),
        migrations.AddConstraint(
            model_name='lobbysession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['waiting', 'active'])), fields=('group',), name='unique_open_lobby_per_group'),
        ),
        migrations.AddConstraint(
            model_name='lobbyparticipant',
            constraint=models.UniqueConstraint(fields=('session', 'user'), name='unique_lobby_participant'),
        ),
        migrations.AddIndex(
            model_name='lobbycard',
            index=models.Index(fields=['session', 'status', 'position'], name='lobby_lobby_session_474679_idx'),
        ),
        migrations.AddConstraint(
            model_name='lobbycard',
            constraint=models.UniqueConstraint(fields=('session', 'movie'), name='unique_lobby_card'),
        ),
        migrations.AddConstraint(
            model_name='lobbycard',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'current')), fields=('session',), name='unique_current_card_per_session'),
        ),
        migrations.AddConstraint(
            model_name='watchlistofferresponse',
            constraint=models.UniqueConstraint(fields=('offer', 'participant'), name='unique_offer_response'),
        ),
    ]
