# Generated by Django 6.0.1 on 2026-04-01 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("groups", "0001_initial"),
        ("movies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmembership",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                related_name="movie_groups", through="groups.GroupMembership", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="groupmovie",
            name="group",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="groups.group"),
        ),
        migrations.AddField(
            model_name="groupmovie",
            name="movie",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="movies.movie"),
        ),
        migrations.AddField(
            model_name="groupmovie",
            name="suggested_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suggestions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="group_movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="groups.groupmovie"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name="groupmembership",
            unique_together={("user", "group")},
        ),
        migrations.AlterUniqueTogether(
            name="groupmovie",
            unique_together={("group", "movie")},
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("group_movie", "user")},
        ),
    ]
