# Generated by Django 6.0.1 on 2026-04-01 19:21

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("movies", "0000_pgvector"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tmdb_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("imdb_id", models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("original_title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "media_type",
                    models.CharField(
                        choices=[("movie", "Movie"), ("series", "Series")], default="movie", max_length=10
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("runtime", models.IntegerField(blank=True, null=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("adult", models.BooleanField(default=False)),
                ("genres", models.TextField(blank=True, null=True)),
                ("keywords", models.TextField(blank=True, null=True)),
                ("director", models.TextField(blank=True, null=True)),
                ("writers", models.TextField(blank=True, null=True)),
                ("actors", models.TextField(blank=True, null=True)),
                ("country", models.TextField(blank=True, null=True)),
                ("poster_path", models.CharField(blank=True, max_length=255, null=True)),
                ("backdrop_path", models.CharField(blank=True, max_length=255, null=True)),
                ("awards", models.TextField(blank=True, null=True)),
                ("revenue", models.BigIntegerField(blank=True, null=True)),
                ("budget", models.BigIntegerField(blank=True, null=True)),
                ("tmdb_score", models.FloatField(blank=True, null=True)),
                ("imdb_score", models.FloatField(blank=True, null=True)),
                ("rottentomato_score", models.CharField(blank=True, max_length=10, null=True)),
                ("metacritic_score", models.CharField(blank=True, max_length=10, null=True)),
                ("filmweb_score", models.FloatField(blank=True, null=True)),
                ("imdb_url", models.URLField(blank=True, null=True)),
                ("rottentomato_url", models.URLField(blank=True, null=True)),
                ("metacritic_url", models.URLField(blank=True, null=True)),
                ("filmweb_url", models.URLField(blank=True, null=True)),
                ("embeddings", pgvector.django.vector.VectorField(blank=True, dimensions=2000, null=True)),
            ],
            options={
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embeddings"],
                        m=16,
                        name="movie_embeddings_hnsw_idx",
                        opclasses=["vector_cosine_ops"],
                    )
                ],
            },
        ),
    ]
