# Generated by Django 6.0.1 on 2026-10-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_alter_movie_embeddings"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="homepage",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="original_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="popularity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="production_companies",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="spoken_languages",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="tagline",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="vote_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
