# Generated by Django 6.0.1 on 2026-10-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_movie_homepage_movie_original_language_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="homepage",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="original_title",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.TextField(),
        ),
    ]
