# Generated by Django 6.0.1 on 2026-10-03 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_homepage_alter_movie_original_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMovieLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchlist_added_at', models.DateTimeField(blank=True, null=True)),
                ('first_watched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_entries', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_library', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'watchlist_added_at'], name='movies_user_user_id_ec268b_idx'), models.Index(fields=['user', 'first_watched_at'], name='movies_user_user_id_50cf83_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'movie'), name='unique_user_movie_library'), models.CheckConstraint(condition=models.Q(('watchlist_added_at__isnull', False), ('first_watched_at__isnull', False), _connector='OR'), name='library_requires_state')],
            },
        ),
    ]
